# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentsapp', '0002_auto_20170622_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='cBirthday',
            field=models.DateField(default='', null=True),
        ),
    ]
