# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentsapp', '0003_auto_20170622_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='cBirthday',
            field=models.DateField(),
        ),
    ]
