# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-09-25 09:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentsapp', '0006_auto_20180925_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='cAddr',
            field=models.CharField(blank=True, editable='False', max_length=255),
        ),
    ]
