# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-09-25 09:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentsapp', '0004_auto_20170622_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='cAddr',
            field=models.CharField(blank=True, default='', editable='True', max_length=255),
        ),
    ]
